### ISSUE TITLE
Allow for Longer Positive Prompts?

### ISSUE THREAD

**Issue by camoody1** [ExponentialML/ComfyUI_VisualStylePrompting#16]
Is it possible to allow for longer positive prompts? 

I kept getting the error:

`RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 1 in the list.`

I had to keep reducing the length of my positive prompt until it was short enough to work successfully.

**Comment by pamparamm** [comment]
You must use the same number of chunks for positive prompt and reference prompt (in your example, positive has 2 chunks and reference has 1).
You can pad tensor in reference prompt from 77 to 154 (from 1 to 2 chunks) by using `Conditioning (Concat)` node applied to reference cond and to empty cond, or by utilizing BREAKs from ` ClipTextEncode++` node from smZnodes extension

**Comment by camoody1** [comment]
Okay, thank you.

Just because I feel like I should ask... Is this something you can check for in the code and correct there if the prompts don't have the same number of chunks? Seems like a lot of people might run into this same issue. 🤷🏼

**Comment by hyupuunos** [comment]
This restriction makes it completely impossible for me to use it
I don't know under what circumstances there would be exactly the same quantity

**Comment by pamparamm** [comment]
Will try to fix this problem by auto-padding with empty conditioning
