### ISSUE TITLE
not found the node.....

### ISSUE THREAD

**Issue by K-O-N-B** [ExponentialML/ComfyUI_VisualStylePrompting#17]
I have installed it via github link
![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/152141077/e9cfd251-acb8-43f5-adc8-d0a610cc6d2d)

but still...

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/152141077/eefceb8f-b37d-4648-b43e-4ae024efe9d8)

**Comment by K-O-N-B** [comment]
updated and download the workflow_simple.json, is this the last version?

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/152141077/c9e3e76f-4272-4b52-9a6b-5c19d3b40589)

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/152141077/9574ca3f-2092-4abe-8c7a-9ea9817ebb72)

**Comment by pamparamm** [comment]
workflow_simple.json in workflows directory is currently outdated, you can download updated workflow from [here](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/blob/3122642cabf0e9d6023fcb9406bd149c09988ae2/workflows/workflow_simple.png)

**Comment by K-O-N-B** [comment]
thank u
