### ISSUE TITLE
Required input is missing

### ISSUE THREAD

**Issue by petercham** [ExponentialML/ComfyUI_VisualStylePrompting#19]
![1711378408390](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/3765653/a5325e22-a539-4929-91da-5bc32e56caf5)
Prompt outputs failed validation
ApplyVisualStyle:
- Required input is missing: reference_cond
- Required input is missing: positive
- Required input is missing: negative

**Comment by pamparamm** [comment]
Try to delete and recreate `Apply Visual Style Prompting` node
