### ISSUE TITLE
Missing "VisualStylePrompt" node

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [ExponentialML/ComfyUI_VisualStylePrompting#23]
After loading the workflow, the "VisualStylePrompt" node appears to be missing. I have updated and reinstalled the custom node.

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/60541708/a9499569-a783-4e3a-8fe7-e7194a6db686)

The "Apply Visual Style Prompting" is fine and shows up.
The extension is loaded successfully in the Comfy booting.

Any suggestions?

**Comment by pamparamm** [comment]
Example workflow is old and isn't working with the current version, will be fixed in #18. Please refer to #17 to get updated workflow

**Comment by MNeMoNiCuZ** [comment]
Ah gotcha.
Yeah that workflow works. Although the workflow doesn't appear to be saved with the image?
So it must be re-created manually.
