### ISSUE TITLE
i have installed this in custom nodes but one node is still missing while loading the provided work flow, its the node which connects with reference_cond

### ISSUE THREAD

**Issue by Manish-cel** [ExponentialML/ComfyUI_VisualStylePrompting#24]

**Comment by Manish-cel** [comment]
![Uploading missing.png…]()

**Comment by acegraphx** [comment]
same here
![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/807445/a8345c0f-fe9f-4cc0-950f-412e34e63601)

**Comment by pamparamm** [comment]
Duplicate of #23.
> Example workflow is old and isn't working with the current version, will be fixed in https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/pull/18. Please refer to https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/issues/17 to get updated workflow
