### ISSUE TITLE
Reference image prompt seems to do nothing

### ISSUE THREAD

**Issue by filliptm** [ExponentialML/ComfyUI_VisualStylePrompting#3]
im running an LCM model at a CFG of 1. I quickly realized that the tool does not work at all with a CFG of 1, but that makes sense due to things not being encoded fully at that value. That being said, I have noticed it works well on LCM with a CFG of 0.5. anything higher than 1 does a pretty lack luster result. 0.5 seems the best

After testing that a bit with different prompts, I found that the reference prompt does nothing at all to the output. This may be to the low CFG value, but I'm not sure

**Comment by ExponentialML** [comment]
One more: 

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/59846140/9040a8d4-a98c-4785-a8e1-93c641298e11)

**Comment by filliptm** [comment]
Definitely working now!
