### ISSUE TITLE
Not Work!

### ISSUE THREAD

**Issue by jesenzhang** [ExponentialML/ComfyUI_VisualStylePrompting#7]
I tried the workflow, not worked!
![workflow (2)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/7984556/df6dbb9d-e880-4aa6-91eb-992fa6247e72)

**Comment by JPW0080** [comment]
It can work though:

![ComfyUIVisualStylePrompting](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/104588046/4b31342e-4c24-448a-9b86-035f85f64270)

**Comment by jesenzhang** [comment]
> It can work though:
> 
> ![ComfyUIVisualStylePrompting](https://private-user-images.githubusercontent.com/104588046/313816313-4b31342e-4c24-448a-9b86-035f85f64270.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTA5MTksIm5iZiI6MTcxMDgxMDYxOSwicGF0aCI6Ii8xMDQ1ODgwNDYvMzEzODE2MzEzLTRiMzEzNDJlLTRjMjQtNDQ4YS05Yjg2LTAzNWY4NWY2NDI3MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTEwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmM1NWJmNGViNTQxY2ZmN2FjZWViZmJiYmMyYjM1NWNiZDU2ZWFlMGE4YWYzMzZiN2YwZTMyOGM1MTgzMWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QrbgMHDvE_sFUSbls2qgvlM61RE8VgecUNcHdckyAF8)

It seems like not working with '--force-fp16' or  sdxl . and I added controlnet , It did a little effect ,no more. How can I get the correct result?
![workflow (3)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/7984556/542515d5-788b-47ca-bf8c-98eebc25e2d3)

**Comment by tanglup** [comment]
> > 但它可以工作：
> > ![ComfyUI视觉风格提示](https://private-user-images.githubusercontent.com/104588046/313816313-4b31342e-4c24-448a-9b86-035f85f64270.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTA5MTksIm5iZiI6MTcxMDgxMDYxOSwicGF0aCI6Ii8xMDQ1ODgwNDYvMzEzODE2MzEzLTRiMzEzNDJlLTRjMjQtNDQ4YS05Yjg2LTAzNWY4NWY2NDI3MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTEwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmM1NWJmNGViNTQxY2ZmN2FjZWViZmJiYmMyYjM1NWNiZDU2ZWFlMGE4YWYzMzZiN2YwZTMyOGM1MTgzMWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QrbgMHDvE_sFUSbls2qgvlM61RE8VgecUNcHdckyAF8)
> 
> 似乎无法使用 '--force-fp16' 或 sdxl 。然后我加了controlnet，起到了一点作用，仅此而已。我怎样才能得到正确的结果？ ![工作流程 (3)](https://private-user-images.githubusercontent.com/7984556/313881853-542515d5-788b-47ca-bf8c-98eebc25e2d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjk4MTcsIm5iZiI6MTcxMDgyOTUxNywicGF0aCI6Ii83OTg0NTU2LzMxMzg4MTg1My01NDI1MTVkNS03ODhiLTQ3Y2EtYmY4Yy05OGVlYmMyNWUyZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDYyNTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYwZDMyZGU0ZDg3NjY2ZDRhOTQ4ZTZkZmM1OTkwOTQ3Yzg4ODUzYjk5OTUxZGVmYjI0YTQ2YTAxYTUyNThjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eEAygKIVspC2MPDA0jiWbLQEdgW4RAMB5iA-K2QgVq4)

“true” off

**Comment by jesenzhang** [comment]
I just can't get satisfactory results.
![workflow (4)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/7984556/194857cf-9974-4f7c-97a7-238601d5ead2)

**Comment by ExponentialML** [comment]
Hey. I can confirm that there's something that's preventing the condition from inferring properly.
I'm busy with some other projects, but I will look to address this soon.

**Comment by shiloh92** [comment]
Yeah the example doesn't seem to work.

**Comment by joshua76y** [comment]
no work too

**Comment by roobt233** [comment]
![微信截图_20240321092714](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/129240042/b7d13ec8-2e29-4957-b281-369532741fb2)
经过大量测试，在目前插件版本下，将“apply visual style prompting"的denoise，和采样器的cfg值降低，会有一定效果，期待作者的下一个版本。

**Comment by ExponentialML** [comment]
Hey everyone here. I've released an update that fixes some bugs, as well as adds an option to select [which blocks to utilize](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/issues/9#issue-2199077769) (thanks @ziyaxuanyi!), so please pull the latest request.  

The block selection at the moment is *"lazy"* in the sense that only the block group is chosen, and not the specific layers recommended in the paper. Using only the output blocks seems to work very well in my tests.

This has only been tested on 1.5 based models, but should work with SDXL as well.

Let me know if anything has improved or if anything is working for you!

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/59846140/7b9b56ad-57d8-49f3-ab5e-a9087259bb98)

**Comment by julien-blanchon** [comment]
This is working but in a pretty chaotic way with the default CFG (7.0/8.0): 2/3 of the time I'm getting not related generation. By taking an higher CFG like 10 I'm now following the prompt more often


<img width="1291" alt="Screenshot 2024-03-22 at 00 04 29" src="https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/aaa9fca5-ba10-415d-9e0a-5b8c532be5ac">
<img width="1291" alt="Screenshot 2024-03-22 at 00 04 49" src="https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/da975390-4e39-4aa1-b16c-f19c249dd197">
<img width="1291" alt="Screenshot 2024-03-22 at 00 05 17" src="https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/743b8e00-1314-4098-92c8-61100c4dd5e0">
<img width="1291" alt="Screenshot 2024-03-22 at 00 05 28" src="https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/f589e3dc-37f1-46ea-886f-eb28dd79f37d">

**Comment by julien-blanchon** [comment]
@ExponentialML, this is very unstable. I have a lot of bleeding between reference content and generation. I'm giving you examples here so we can debug this together.

![workflow (1)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/1ee76427-4215-4e59-bade-a8593231d8a5)
![workflow (2)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/c99dc1df-e93a-48d3-bbae-15c181b0530c)

Workflow is in the screenshot payload if you want to reproduce

**Comment by ExponentialML** [comment]
There is in ComfyUI that's not updating the state of my node (you have to reload the model on each prompt / settings change), but other than that it seems to be working as intended.

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/59846140/4c467dd6-caa4-4d48-a2aa-860b5ec09da9)

**Comment by ExponentialML** [comment]
I applied a major update. Please read the main README and use the updated workflow.

**Comment by jesenzhang** [comment]
test on sdxl ,It seems that there is still room for improvement.
![visualstyleprompt](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/7984556/1f6bcfb9-d565-45a0-8af3-b9df60c1d8ca)

**Comment by julien-blanchon** [comment]
The new version did work at first try for my example!!! 

Huge kudo to you @ExponentialML, I really like your job here <3.

Screenshot with payload here:
![workflow (3)](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/11278197/19c7d3ec-1407-43bd-9a41-6f1d6da6741e)
