### ISSUE TITLE
Has the switching self-attention been applied to all stages?

### ISSUE THREAD

**Issue by ziyaxuanyi** [ExponentialML/ComfyUI_VisualStylePrompting#9]
The paper said the switching self-attention should only be applied to late upblocks of Unet to achieve the best results.
But this codes seem that the switching self-attention is applied to all stages.

**Comment by ExponentialML** [comment]
This seems to be the [case](https://github.com/naver-ai/Visual-Style-Prompting/blob/9f09135f8f9edfd0fc8d9adc811ad1e18c675329/pipelines/inverted_ve_pipeline.py#L1393)! Completely overlooked it.

![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/59846140/f08f079b-5ae5-49ee-8ce8-4e861bf61521)

**Comment by ExponentialML** [comment]
I'm going to close this as this functionality has been implemented. 

Please feel free to ping again if there are any concerns that relate to this issue.
